version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/frontend/releases/new-release/

permissions:
  - object: /home/ec2-user/frontend/releases/new-release
    pattern: '**'
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/setup_directories.sh
      timeout: 30
      runas: ec2-user
  AfterInstall:
    - location: scripts/change_symlink.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart_service.sh
      timeout: 30
      runas: ec2-user
