version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/frontend
    overwrite: yes
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
