# 위치 ~/frontend/.github/workflows
# 워크플로우의 이름을 지정합니다. GitHub Actions 탭에서 이 이름으로 표시됩니다.
name: Deploy to AWS EC2
# 워크플로우가 실행될 조건을 지정합니다. 여기서는 main 브랜치에 push가 발생할 때 실행됩니다.
on:
  push:
    branches:
      - main # 어떤 브랜치가 푸시 됬을때 배포가 될지 설정

# 실제 실행될 작업들을 정의합니다.
jobs:
  deploy:
    # 워크플로우가 실행될 환경을 지정합니다.
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소의 코드를 워크플로우 환경으로 가져옵니다.
      - uses: actions/checkout@v2

      # Node.js를 설치하고 설정합니다.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # 서버와 동일한 메이저 버전 사용 -> ec2 node 버전은 '22.13.1'

      # pnpm을 설치하고 설정합니다.
      - name: Setup pnpm # npm 대신 pnpm 을 사용하기로 했다.
        uses: pnpm/action-setup@v2
        with:
          version: 9 # 서버와 동일한 메이저 버전 사용 -> ec2에서 사용하는 pnpm 버전은 9.15.1

      # 프로젝트 의존성을 설치합니다.
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Next.js 애플리케이션을 빌드합니다.
      - name: Build application
        run: pnpm build

      # EC2 서버에 배포합니다.
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          # GitHub Secrets에 설정된 값들을 사용합니다.
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}

          # EC2 서버에서 실행할 명령어들을 정의합니다.
          script: |
            cd ~/frontend
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm build
            pm2 reload ecosystem.config.js
