# .github/workflows/main.yml
name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: s3-clipvault
  CODE_DEPLOY_APPLICATION_NAME: codeDeploy-clipVault
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: codeDeploy-clipVault-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Get short Git SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create deployment package
        run: |
          mkdir deploy-package
          cp -r .next package.json ecosystem.config.js public scripts appspec.yml deploy-package/ || echo "Failed to copy files"
          cd deploy-package && zip -r ../frontend-build-${{ env.GIT_SHA }}.zip . || echo "Failed to create zip"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          # zip 파일 내용 확인 (문제 발생 시 디버깅을 위해 유지)
          unzip -l frontend-build-${{ env.GIT_SHA }}.zip
          # S3에 업로드
          aws s3 cp frontend-build-${{ env.GIT_SHA }}.zip s3://${{ env.S3_BUCKET_NAME }}/frontend/frontend-build-${{ env.GIT_SHA }}.zip

      # - name: Start CodeDeploy Deployment
      #   run: |
      #     aws deploy create-deployment \
      #       --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
      #       --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
      #       --s3-location bucket=${{ env.S3_BUCKET_NAME }},bundleType=zip,key=frontend/frontend-build-${{ env.GIT_SHA }}.zip
